= Product Enablement: Ansible Automation Platform Operator Deployment
:navtitle: Home

== Overview

The Ansible Automation Platform Operator Deployment provides a comprehensive, hands-on learning experience for Red Hat Ansible Automation Platform (AAP). This lab covers the full spectrum of automation development, from basic concepts to advanced CI/CD pipelines, infrastructure as code, Event Driven Ansible and lastly an exploration of some of the AI integration within Ansible Automation Platform.

== Prerequisites

Before starting this lab, ensure you have:

* Basic understanding of Linux command line operations
* Familiarity with YAML syntax
* Knowledge of fundamental networking concepts
* Access to the Red Hat Demo Platform environment

== Learning Outcomes

By the end of this lab, you will be able to:

* Set up and configure development environments for Ansible automation.
* Deploy and manage AAP across different platforms.
* Using Config as Code to manage Ansible content and configurations.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

 - Andrew Block (Subject Matter Expert)
 - Amrinder Singh (Content Architect)
 - Anna Swicegood (Learning Product Manager)