= Product Enablement: Ansible Automation Platform Operator Deployment
:navtitle: Home

== Overview

The Ansible Automation Platform Operator provides cloud-native, push-button deployment of new Ansible Automation Platform instances in your OpenShift environment and this lab covers the full spectrum of automation development where we will explore how to manage Ansible Automation Platform (AAP) configurations declaratively as code using Ansible playbooks and the infra.aap_configuration and infra.aap_utilities collections. instead of manually configuring settings through the AAP user interface (ClickOps).

== Prerequisites

Before starting this lab, ensure you have:

* Basic understanding of Linux command line operations
* Familiarity with YAML syntax
* Knowledge of fundamental networking concepts
* Access to the Red Hat Demo Platform environment

== Learning Outcomes

By the end of this lab, you will be able to:

* Set up and configure development environments for Ansible automation.
* Deploy and manage AAP across different platforms.
* Using Config as Code to manage Ansible content and configurations.

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

 - Andrew Block (Subject Matter Expert)
 - Amrinder Singh (Content Architect)
 - Anna Swicegood (Learning Product Manager)