= Ansible Automation Platform on OpenShift

The Ansible Automation Platform Operator provides cloud-native, push-button deployment of new Ansible Automation Platform instances in your OpenShift environment. The Ansible Automation Platform Operator includes resource types to deploy and manage instances of automation controller and private automation hub. It also includes automation controller job resources for defining and launching jobs inside your automation controller deployments.

Deploying Ansible Automation Platform instances with a Kubernetes native operator offers several advantages over launching instances from a playbook deployed on Red Hat OpenShift Container Platform, including upgrades and full lifecycle support for your Red Hat Ansible Automation Platform deployments.

More information can be found on the official link:https://docs.redhat.com/en/documentation/red_hat_ansible_automation_platform/2.5/html/installing_on_openshift_container_platform/index[AAP on OpenShift documentation,window=_blank].

== Learning Objectives

After completing this module, you will be able to:

* Navigate and understand AAP operator deployments on OpenShift
* Deploy custom AAP instances using the AAP operator
* Customize AAP configurations and deployments
* Troubleshoot operator-managed AAP installations
* Understand AAP operator lifecycle management
